import 'bootstrap/dist/css/bootstrap.min.css';
import '../styles/globals.scss';
import "../styles/components.scss"
import "../styles/app.scss"
import "../styles/routes.scss"
import "../styles/blog.scss"
import Navbar from '@/components/Navbar';
import Footer from '@/components/Footer';

export const metadata = {
  title: 'Rajasthan Tour Packages',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
