import 'bootstrap/dist/css/bootstrap.min.css';
import '../styles/globals.scss';
import "../styles/components.scss";
import "../styles/app.scss";
import "../styles/routes.scss";
import "../styles/blog.scss";
import Footer from '@/components/Footer';
import Navbar from '@/components/Navbar';

// Metadata for the application
export const metadata = {
  title: 'Rajasthan Tour Packages',
  description: 'Generated by create next app',
  icons: {
    icon: '/rajasthan-travel-helpline.png', // This is where you set your favicon
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        {/* Preloading Google Fonts */}
        <link
          rel="preload"
          href="https://fonts.googleapis.com/css2?family=Poppins:wght@100;200;300;400;500;600;700;800;900&family=Lobster&display=swap"
          as="style"
        />
        {/* Apply the font after preload */}
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Poppins:wght@100;200;300;400;500;600;700;800;900&family=Lobster&display=swap"
        />
        <noscript>
          {/* Fallback if JavaScript is disabled */}
          <link
            rel="stylesheet"
            href="https://fonts.googleapis.com/css2?family=Poppins:wght@100;200;300;400;500;600;700;800;900&family=Lobster&display=swap"
          />
        </noscript>
      </head>
      <body>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
