name: Build and Deploy the App

on:
  push:
    branches:
      - master # Trigger on pushes to the master branch

jobs:
  # Job: Build the Application
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      # Step 3: Install dependencies
      - name: Install Dependencies
        run: npm ci

      # Step 4: Build the App
      - name: Build the App
        run: |
          npm run build

      # Step 5: Notify Build Success
      - name: Notify Build Success
        if: ${{ success() }}
        run: echo "Build completed successfully! Deployment is in progress by Vercel."

      # Step 6: Notify Build Failure
      - name: Notify Build Failure
        if: ${{ failure() }}
        run: echo "Build failed. Please check the logs."

      # Step 7: Confirm Deployment Ready
      - name: Confirm Deployment
        if: ${{ success() }}
        run: |
          echo "The app has been deployed successfully via Vercel. 🎉"
          echo "Your live application is available at: https://www.rajasthantourpackages.in"

      # Step 7: Set Live URL as Output
      - name: Set Live URL Output
        if: ${{ success() }}
        run: echo "LIVE_URL=https://www.rajasthantourpackages.in" >> $GITHUB_ENV

      # Step 8: Output the Live URL
      - name: Output Live URL
        if: ${{ success() }}
        run: echo "https://www.rajasthantourpackages.in"
